groups:
  - name: url-shortener-alerts
    rules:
      # High Error Rate Alert
      - alert: HighErrorRate
        expr: |
          (
            rate(http_requests_total{status=~"5.."}[5m]) /
            rate(http_requests_total[5m])
          ) * 100 > 5
        for: 2m
        labels:
          severity: critical
          service: url-shortener
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }}% which is above the 5% threshold"

      # High Response Time Alert
      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
          service: url-shortener
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s"

      # High Memory Usage Alert
      - alert: HighMemoryUsage
        expr: |
          (process_resident_memory_bytes / (200 * 1024 * 1024)) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: url-shortener
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}% of allocated limit"

      # Service Down Alert
      - alert: ServiceDown
        expr: up{job="url-shortener-api"} == 0
        for: 1m
        labels:
          severity: critical
          service: url-shortener
        annotations:
          summary: "URL Shortener service is down"
          description: "The URL Shortener API service has been down for more than 1 minute"

      # Database Connection Alert
      - alert: DatabaseConnectionFailed
        expr: up{job="mongodb"} == 0
        for: 2m
        labels:
          severity: critical
          service: mongodb
        annotations:
          summary: "Database connection failed"
          description: "Cannot connect to MongoDB database"

      # High CPU Usage Alert
      - alert: HighCPUUsage
        expr: |
          (rate(process_cpu_seconds_total[5m]) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: url-shortener
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}%"

      # Low Disk Space Alert
      - alert: LowDiskSpace
        expr: |
          (node_filesystem_free_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"}) * 100 < 20
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Low disk space"
          description: "Disk space is {{ $value }}% full"
